version: "3.12"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: python3 app.py 
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py