"""Make incident type nullable

Revision ID: 8263a2e88d5f
Revises: 7c053c563632
Create Date: 2025-07-17 17:44:17.293215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8263a2e88d5f'
down_revision = '7c053c563632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
